- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Perform WinRM ping to test WinRM connection
      win_ping:

    # - name: Debug Script
    #   debug:
    #     var: ansible_facts['discovered_interpreter_python']

    # - name: start httpd
    #   ansible.builtin.service:
    #     name: httpd
    #     state: started
